// <auto-generated />
namespace web_api_version01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FourthMigration1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FourthMigration1));
        
        string IMigrationMetadata.Id
        {
            get { return "201807181505009_FourthMigration1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
